import { useEffect, useState, type Dispatch, type SetStateAction } from "react";
import { Alert, Box, Button, Card, CardContent, IconButton, MenuItem, TextField, Typography } from "@mui/material";
import { schemaApi } from "../api";
import type { ParameterDefinition, RequestSchema } from "../types";
import { getErrorMessage } from "../utils";
function Svg({type}:{type:"add"|"delete"}){return <Box component="svg" viewBox="0 0 24 24" sx={{width:19,height:19,fill:"none",stroke:"currentColor",strokeWidth:1.9,strokeLinecap:"round",strokeLinejoin:"round"}}>{type==="add"?<><path d="M12 5v14M5 12h14"/></>:<><path d="M4 7h16M10 11v6M14 11v6M6 7l1 14h10l1-14M9 7V4h6v3"/></>}</Box>}
const blank=():ParameterDefinition=>({name:"",type:"string",required:false,description:"",default:null,example:null});
export default function ContractEditor({mockId,versionId}:{mockId:string;versionId:string}){const [schema,setSchema]=useState<RequestSchema|null>(null);const [query,setQuery]=useState<ParameterDefinition[]>([]);const [path,setPath]=useState<ParameterDefinition[]>([]);const [headers,setHeaders]=useState<ParameterDefinition[]>([]);const [body,setBody]=useState("{}");const [error,setError]=useState("");const [saving,setSaving]=useState(false);useEffect(()=>{const load=async()=>{try{const r=await schemaApi.get(mockId,versionId);setSchema(r.data);setQuery(r.data.query_parameters||[]);setPath(r.data.path_parameters||[]);setHeaders(r.data.headers||[]);setBody(JSON.stringify(r.data.body_schema??{},null,2))}catch(e){const status=(e as any)?.response?.status;if(status!==404)setError(getErrorMessage(e))}};void load()},[mockId,versionId]);const save=async()=>{try{setSaving(true);setError("");const data={query_parameters:query,path_parameters:path,headers,body_schema:body.trim()?JSON.parse(body):null};if(schema)await schemaApi.update(mockId,versionId,data);else{const r=await schemaApi.create(mockId,versionId,data);setSchema(r.data)}}catch(e){setError(e instanceof SyntaxError?"Body schema must be valid JSON.":getErrorMessage(e))}finally{setSaving(false)}};return <Box>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<ParameterSection title="Query parameters" items={query} setItems={setQuery}/><ParameterSection title="Path parameters" items={path} setItems={setPath}/><ParameterSection title="Headers" items={headers} setItems={setHeaders}/><Typography variant="h6" sx={{fontWeight:900,mt:3}}>Body schema</Typography><Typography sx={{fontSize:12,color:"text.secondary",mb:1}}>Stored as a JSON object and enforced by the backend request validator.</Typography><TextField fullWidth multiline minRows={10} value={body} onChange={e=>setBody(e.target.value)} sx={{"& textarea":{fontFamily:"monospace",fontSize:12}}}/><Box sx={{display:"flex",justifyContent:"flex-end",mt:2}}><Button variant="contained" onClick={()=>void save()} disabled={saving}>{saving?"Saving…":schema?"Save contract":"Create contract"}</Button></Box></Box>}
function ParameterSection({title,items,setItems}:{title:string;items:ParameterDefinition[];setItems:Dispatch<SetStateAction<ParameterDefinition[]>>}){const update=(i:number,key:keyof ParameterDefinition,value:unknown)=>setItems(old=>old.map((x,n)=>n===i?{...x,[key]:value}:x));return <Box sx={{mt:3}}><Box sx={{display:"flex",justifyContent:"space-between",alignItems:"center",mb:1.2}}><Box><Typography variant="h6" sx={{fontWeight:900}}>{title}</Typography><Typography sx={{fontSize:11,color:"text.secondary"}}>{items.length} configured</Typography></Box><Button size="small" startIcon={<Svg type="add"/>} onClick={()=>setItems(old=>[...old,blank()])}>Add field</Button></Box><Box sx={{display:"grid",gap:1}}>{items.map((item,i)=><Card key={`${item.name}-${i}`} variant="outlined"><CardContent sx={{p:1.3,"&:last-child":{pb:1.3},display:"grid",gridTemplateColumns:{xs:"1fr",md:"1.3fr .8fr .8fr 1.4fr 1fr 1fr auto"},gap:1}}><TextField label="Name" value={item.name} onChange={e=>update(i,"name",e.target.value)}/><TextField select label="Type" value={item.type||"string"} onChange={e=>update(i,"type",e.target.value)}>{["string","integer","number","boolean","object","array"].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField select label="Required" value={item.required?"yes":"no"} onChange={e=>update(i,"required",e.target.value==="yes") }><MenuItem value="no">No</MenuItem><MenuItem value="yes">Yes</MenuItem></TextField><TextField label="Description" value={item.description||""} onChange={e=>update(i,"description",e.target.value)}/><TextField label="Default" value={item.default==null?"":String(item.default)} onChange={e=>update(i,"default",e.target.value||null)}/><TextField label="Example" value={item.example==null?"":String(item.example)} onChange={e=>update(i,"example",e.target.value||null)}/><IconButton color="error" onClick={()=>setItems(old=>old.filter((_,n)=>n!==i))}><Svg type="delete"/></IconButton></CardContent></Card>)}</Box></Box>}
