import { useState } from "react";
import { Box, Button, Chip, Collapse, Divider, IconButton, Typography } from "@mui/material";
import { useNavigate } from "react-router-dom";
import type { APIVersion, MockAPI } from "../types";
import { versionApi } from "../api";
import StatusChip from "./StatusChip";
import { getErrorMessage } from "../utils";
function Svg({type}:{type:"expand"|"tune"|"delete"}){const p={expand:<path d="m6 9 6 6 6-6"/>,tune:<><path d="M4 6h16M4 12h16M4 18h16"/><circle cx="9" cy="6" r="2"/><circle cx="15" cy="12" r="2"/><circle cx="10" cy="18" r="2"/></>,delete:<><path d="M4 7h16M10 11v6M14 11v6M6 7l1 14h10l1-14M9 7V4h6v3"/></>};return <Box component="svg" viewBox="0 0 24 24" sx={{width:19,height:19,fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round",strokeLinejoin:"round"}}>{p[type]}</Box>}
export default function VersionPanel({api,version,onRefresh}:{api:MockAPI;version:APIVersion;onRefresh:()=>void}){const [open,setOpen]=useState(false);const [error,setError]=useState("");const nav=useNavigate();const remove=async()=>{if(!confirm(`Delete ${version.version}?`))return;try{await versionApi.remove(api.id,version.id);onRefresh()}catch(e){setError(getErrorMessage(e))}};const toggle=async()=>{try{await versionApi.update(api.id,version.id,{is_active:!version.is_active});onRefresh()}catch(e){setError(getErrorMessage(e))}};return <Box sx={{border:"1px solid rgba(255,255,255,.07)",borderRadius:2,mb:1.5,overflow:"hidden"}}><Box sx={{p:1.8,display:"flex",alignItems:"center",gap:1.2,flexWrap:"wrap"}}><IconButton onClick={()=>setOpen(!open)} sx={{transform:open?"rotate(180deg)":"none",transition:".2s"}}><Svg type="expand"/></IconButton><Box sx={{flex:1,minWidth:160}}><Box sx={{display:"flex",alignItems:"center",gap:1}}><Typography sx={{fontFamily:"monospace",fontWeight:900}}>{version.version}</Typography><StatusChip active={version.is_active}/></Box><Typography sx={{fontSize:10,color:"text.secondary"}}>Created {new Date(version.created_at).toLocaleString()}</Typography></Box><Button size="small" onClick={()=>void toggle()}>{version.is_active?"Deactivate":"Activate"}</Button><Button size="small" startIcon={<Svg type="tune"/>} onClick={()=>nav(`/apis/${api.id}/versions/${version.id}`)}>Configure</Button><IconButton color="error" onClick={()=>void remove()}><Svg type="delete"/></IconButton></Box>{error&&<Typography sx={{px:2,pb:1,color:"error.main",fontSize:11}}>{error}</Typography>}<Collapse in={open}><Divider/><Box sx={{p:2}}><Typography sx={{fontSize:10,color:"text.secondary"}}>VERSION ID</Typography><Typography sx={{fontFamily:"monospace",fontSize:11,mt:.5,overflowWrap:"anywhere"}}>{version.id}</Typography></Box></Collapse></Box>}
