import { useEffect, useState } from "react";
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, TextField, Typography } from "@mui/material";
import { useNavigate, useParams } from "react-router-dom";
import PageHeader from "../components/PageHeader";
import StatusChip from "../components/StatusChip";
import VersionPanel from "../components/VersionPanel";
import { mockApi, versionApi } from "../api";
import type { APIVersion, MockAPI } from "../types";
import { getErrorMessage } from "../utils";
export default function ApiDetail(){const {id=""}=useParams();const nav=useNavigate();const [api,setApi]=useState<MockAPI|null>(null);const [versions,setVersions]=useState<APIVersion[]>([]);const [error,setError]=useState("");const [dialog,setDialog]=useState(false);const [version,setVersion]=useState("v1");
const load=async()=>{try{const [a,v]=await Promise.all([mockApi.get(id),versionApi.list(id,{page:1,page_size:100})]);setApi(a.data);setVersions(v.data.items)}catch(e){setError(getErrorMessage(e))}};useEffect(()=>{void load()},[id]);
const create=async()=>{try{await versionApi.create(id,{version,is_active:true});setDialog(false);setVersion("v1");await load()}catch(e){setError(getErrorMessage(e))}};
if(!api)return <Box sx={{p:5}}>{error?<Alert severity="error">{error}</Alert>:"Loading…"}</Box>;return <Box sx={{p:{xs:2.5,md:5}}}><PageHeader eyebrow="MOCKPILOT / API DETAIL" title={api.name} subtitle={api.description||"Configure the persisted API definition and its runtime versions."} action={<Button onClick={()=>nav("/apis")}>Back to APIs</Button>}/>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",lg:".8fr 1.2fr"},gap:2}}><Card><CardContent sx={{p:3}}><Typography variant="h6" sx={{fontWeight:900}}>Backend definition</Typography><Box sx={{mt:2,display:"grid",gap:1}}><Info label="ID" value={api.id}/><Info label="Endpoint" value={`/mock${api.base_path}`}/><Info label="Method" value={api.http_method}/><Info label="Owner" value={api.user_id}/><Info label="Access" value={api.is_private?"Private":"Public"}/><Info label="Created" value={new Date(api.created_at).toLocaleString()}/><Info label="Updated" value={new Date(api.updated_at).toLocaleString()}/></Box><Box sx={{mt:2,display:"flex",gap:1}}><StatusChip active={api.is_active}/><Chip label={api.is_private?"PRIVATE":"PUBLIC"} size="small" variant="outlined"/></Box></CardContent></Card><Card><CardContent sx={{p:3}}><Box sx={{display:"flex",justifyContent:"space-between",alignItems:"center",mb:2}}><Box><Typography variant="h6" sx={{fontWeight:900}}>API versions</Typography><Typography sx={{fontSize:12,color:"text.secondary"}}>Versions are persisted by the backend and used by the dynamic mock runtime.</Typography></Box><Button variant="contained" onClick={()=>setDialog(true)}>Add version</Button></Box>{versions.map(v=><VersionPanel key={v.id} api={api} version={v} onRefresh={()=>void load()}/>)}{versions.length===0&&<Typography sx={{py:5,color:"text.secondary"}}>No versions yet.</Typography>}</CardContent></Card></Box><Dialog open={dialog} onClose={()=>setDialog(false)} fullWidth maxWidth="xs"><DialogTitle sx={{fontWeight:900}}>Create API version</DialogTitle><DialogContent sx={{pt:"12px !important"}}><TextField autoFocus fullWidth label="Version" value={version} onChange={e=>setVersion(e.target.value)} placeholder="v1" helperText="The backend normalizes values to v-prefixed versions."/></DialogContent><DialogActions sx={{p:2}}><Button onClick={()=>setDialog(false)}>Cancel</Button><Button variant="contained" onClick={()=>void create()} disabled={!version.trim()}>Create</Button></DialogActions></Dialog></Box>}
function Info({label,value}:{label:string;value:string}){return <Box sx={{display:"grid",gridTemplateColumns:"100px 1fr",gap:1,p:1.2,bgcolor:"rgba(255,255,255,.025)",borderRadius:1.5}}><Typography sx={{fontSize:10,color:"text.secondary"}}>{label}</Typography><Typography sx={{fontFamily:"monospace",fontSize:11,overflowWrap:"anywhere"}}>{value}</Typography></Box>}
