import { useState } from "react";
import { Alert, Box, Button, Card, CardContent, Divider, TextField, Typography } from "@mui/material";
import { useNavigate } from "react-router-dom";
import Logo from "../components/Logo";
import { authApi } from "../api";
import { getErrorMessage } from "../utils";

export default function Login(){const navigate=useNavigate();const [register,setRegister]=useState(false);const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [name,setName]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);
const submit=async()=>{try{setLoading(true);setError("");if(register){await authApi.register({email,password,full_name:name});}const token=(await authApi.login({email,password})).data.access_token;localStorage.setItem("mockpilot_token",token);const me=(await authApi.me()).data;localStorage.setItem("mockpilot_user",JSON.stringify(me));navigate("/dashboard",{replace:true});}catch(e){setError(getErrorMessage(e));}finally{setLoading(false)}};
return <Box sx={{minHeight:"100vh",display:"grid",placeItems:"center",p:2,bg:"#06080b",backgroundImage:"radial-gradient(circle at 15% 15%,rgba(184,255,61,.08),transparent 30%),radial-gradient(circle at 85% 80%,rgba(0,212,255,.07),transparent 30%)"}}><Box sx={{width:"100%",maxWidth:430}}><Box sx={{mb:3,display:"flex",justifyContent:"center"}}><Logo/></Box><Card><CardContent sx={{p:{xs:3,sm:4}}}><Typography variant="h4" sx={{fontWeight:900,mb:.7}}>{register?"Create workspace":"Welcome back"}</Typography><Typography sx={{fontSize:13,color:"text.secondary",mb:3}}>{register?"Create your account and start simulating APIs.":"Connect to your API simulation workspace."}</Typography>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{register&&<TextField fullWidth label="Full name" value={name} onChange={e=>setName(e.target.value)} sx={{mb:1.5}}/>}<TextField fullWidth type="email" label="Email" value={email} onChange={e=>setEmail(e.target.value)} sx={{mb:1.5}}/><TextField fullWidth type="password" label="Password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void submit()}} sx={{mb:2}}/><Button fullWidth variant="contained" size="large" onClick={()=>void submit()} disabled={loading||!email||!password||(register&&!name)}>{loading?"Please wait...":register?"Create account":"Sign in"}</Button><Divider sx={{my:3}}/><Button fullWidth variant="text" onClick={()=>{setRegister(!register);setError("")}}>{register?"Already have an account? Sign in":"Need an account? Create one"}</Button></CardContent></Card><Typography sx={{textAlign:"center",fontSize:10,color:"text.secondary",mt:2}}>FastAPI backend · JWT authentication · MySQL · Redis</Typography></Box></Box>}
